version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: esunDB
      MYSQL_USER: osper
      MYSQL_PASSWORD: testpassword
    networks:
      - esun_app-network

  springboot:
    image: esun_project
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.17.0.2:3306/esunDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: osper
      SPRING_DATASOURCE_PASSWORD: testpassword
    depends_on:
      - mysql
    networks:
      - esun_app-network

networks:
  esun_app-network:
    external: true
    driver: bridge